#spring:
#profiles:
#  active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.c6bufybdvlhw.ap-southeast-1.rds.amazonaws.com:5432/cdsproject
    username: kevinliem
    password: Nicholaskevin11
    pool-size: 30